# Generated by Django 4.1.2 on 2022-10-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
                ('prioridade', models.IntegerField(choices=[(0, 'NENHUMA'), (1, 'ALTA'), (2, 'MÉDIA'), (3, 'BAIXA')], default=0, max_length=1)),
                ('data', models.DateField(null=True)),
                ('feita', models.BooleanField(default=False)),
            ],
        ),
    ]
