# Generated by Django 4.1.2 on 2022-10-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='listas',
            name='tipos',
            field=models.CharField(choices=[('Tarefas', 'Lista de Tarefas'), ('Supermercado', 'Lista de Supermercado')], default='Tarefas', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
