# Generated by Django 4.1.2 on 2022-10-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0003_listas_tipos_alter_tarefa_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listas',
            name='tipos',
        ),
    ]
